"""trying to fix an error in the migration

Revision ID: 60daada52a49
Revises: ae529c5ac723
Create Date: 2023-05-04 12:51:00.685184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60daada52a49'
down_revision = 'ae529c5ac723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
